"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Camera, CheckCircle2, ImagePlus, LockKeyhole, ScanLine, ShieldAlert, Trash2 } from "lucide-react";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";

import { Button, Card, ErrorState, LoadingState } from "@/components/primitives";
import { analyzePose, type ScanAnalysis } from "@/lib/cv";
import { api, formatNumber } from "@/lib/api";

type Assessment = { id: string; captured_at: string; capture_type: string; model_version: string; feature_schema_version: string; quality_score: number; confidence: number; quality_flags: string[]; derived_features: Record<string, number>; raw_media_stored: boolean; disclaimer: string };

export default function BodyScanPage() {
  const queryClient = useQueryClient(); const imageRef = useRef<HTMLImageElement>(null); const [preview, setPreview] = useState(""); const [imageReady, setImageReady] = useState(false); const [analysis, setAnalysis] = useState<ScanAnalysis | null>(null); const [analyzing, setAnalyzing] = useState(false); const [error, setError] = useState("");
  const history = useQuery({ queryKey: ["cv-assessments"], queryFn: () => api<{ items: Assessment[] }>("/cv/assessments") });
  const save = useMutation({ mutationFn: async () => { await api("/privacy/consents/cv_processing", { method: "PUT", body: JSON.stringify({ granted: true, version: "1.0" }) }); return api("/cv/assessments", { method: "POST", body: JSON.stringify({ capture_type: "front", model_version: analysis!.modelVersion, feature_schema_version: "pose-ratios-v1", quality_score: analysis!.qualityScore, confidence: analysis!.confidence, quality_flags: analysis!.qualityFlags, derived_features: analysis!.features, raw_media_stored: false }) }); }, onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["cv-assessments"] }); setPreview(""); setAnalysis(null); } });
  const remove = useMutation({ mutationFn: (id: string) => api(`/cv/assessments/${id}`, { method: "DELETE" }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["cv-assessments"] }) });
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview); }, [preview]);
  function choose(file?: File) { if (!file) return; if (!file.type.startsWith("image/")) { setError("Choose an image file."); return; } if (file.size > 12 * 1024 * 1024) { setError("Use an image smaller than 12 MB."); return; } if (preview) URL.revokeObjectURL(preview); setImageReady(false); setPreview(URL.createObjectURL(file)); setAnalysis(null); setError(""); }
  async function runAnalysis() { if (!imageRef.current) return; setAnalyzing(true); setError(""); try { setAnalysis(await analyzePose(imageRef.current)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Visual analysis could not run."); } finally { setAnalyzing(false); } }
  return <><header className="page-head"><div><span className="eyebrow">Optional visual progress</span><h1>Body scan</h1><p>Browser-side pose geometry for repeatable progress context—never diagnosis or medical body composition.</p></div></header>
    <div className="scan-grid"><Card className="scan-upload"><div className="upload-drop">{preview ? <Image ref={imageRef} src={preview} alt="Selected front-view scan, processed only in this browser" fill unoptimized onLoad={() => setImageReady(true)} /> : <><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => choose(event.target.files?.[0])} aria-label="Choose a front-view progress image" /><div><span className="choice-icon" style={{ marginInline: "auto" }}><ImagePlus size={22} /></span><h3>Choose a front-view image</h3><p className="tiny">Neutral stance, arms slightly separated, camera level at chest height, even lighting.</p></div></>} {preview && <div className="upload-overlay"><Camera size={22} /><p className="tiny">The image stays in this browser. Smaller photos are prepared locally before pose detection.</p><Button onClick={runAnalysis} disabled={analyzing || !imageReady}>{!imageReady ? "Preparing image…" : analyzing ? "Loading pose model…" : "Analyze on this device"}</Button></div>}</div>{error && <p className="field-error" role="alert" style={{ margin: "14px 0 0" }}>{error}</p>}</Card>
      <aside className="scan-side"><Card><span className="eyebrow"><ScanLine size={13} style={{ display: "inline" }} /> Quality gate</span>{analysis ? <><div className="quality-score">{analysis.qualityScore}<small className="tiny"> / 100</small></div><span className={`pill ${analysis.qualityScore >= 60 ? "pill-success" : "pill-warning"}`}>{analysis.qualityScore >= 60 ? <CheckCircle2 size={13} /> : <ShieldAlert size={13} />} {analysis.qualityScore >= 60 ? "Comparable capture" : "Retake recommended"}</span><div className="feature-list"><div className="feature-row"><span>Landmark confidence</span><strong>{Math.round(analysis.confidence * 100)}%</strong></div>{Object.entries(analysis.features).map(([key, value]) => <div className="feature-row" key={key}><span>{key.replaceAll("_", " ")}</span><strong>{formatNumber(value, 3)}</strong></div>)}</div>{analysis.qualityFlags.map((flag) => <p className="tiny" key={flag}>• {flag}</p>)}<Button className="button-wide" style={{ marginTop: 14 }} disabled={save.isPending || analysis.qualityScore < 60} onClick={() => save.mutate()}>{save.isPending ? "Saving derived data…" : "Save derived result"}</Button></> : <p className="tiny" style={{ marginTop: 15 }}>Choose an image to run the framing and landmark-confidence checks.</p>}</Card>
        <Card><span className="eyebrow"><LockKeyhole size={13} style={{ display: "inline" }} /> Privacy & limitations</span><p className="tiny" style={{ marginTop: 13 }}>Raw media is not uploaded or stored. Results are approximate 2D signals affected by camera distance, clothing, pose, lighting and lens distortion. AthleteOS does not diagnose posture, infer body type, or claim clinically validated body-fat accuracy.</p></Card></aside></div>
    <div className="section-title"><h2>Scan timeline</h2><span className="tiny">Derived-only records</span></div>
    {history.isLoading ? <LoadingState label="Loading scan history…" /> : history.isError ? <ErrorState message={history.error.message} /> : history.data?.items.length ? <div className="plan-grid">{history.data.items.map((item) => <Card className="day-card" key={item.id}><span className={`pill ${item.quality_score >= 60 ? "pill-success" : "pill-warning"}`}>{item.quality_score} quality</span><h3>{new Date(item.captured_at).toLocaleDateString()}</h3><span className="tiny">Confidence {Math.round(item.confidence * 100)}% · {Object.keys(item.derived_features).length} comparable features</span><ul className="report-list">{Object.entries(item.derived_features).slice(0, 4).map(([key, value]) => <li key={key}><span>{key.replaceAll("_", " ")}</span><strong>{formatNumber(value, 3)}</strong></li>)}</ul><Button variant="danger" onClick={() => remove.mutate(item.id)}><Trash2 size={15} /> Delete record</Button></Card>)}</div> : <Card className="empty-state"><ScanLine size={24} /><h3>No derived scans yet</h3><p>Your training and progress tracking work fully without visual analysis.</p></Card>}
  </>;
}
