"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, BarChart3, Dumbbell, Flame, Plus, Scale, TrendingUp } from "lucide-react";
import { FormEvent, useState } from "react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

import { Button, Card, ErrorState, LoadingState, MetricCard } from "@/components/primitives";
import { api, formatNumber, todayIso } from "@/lib/api";

type Report = { period: { from: string; to: string }; training: { sessions_started: number; sessions_completed: number; sets_completed: number; volume_kg: number }; body: { weight_series: Array<{ date: string; value: number }>; weight_change_kg: number | null }; habits: { completions: number; completion_rate: number }; data_note: string };
type Metric = { id: string; measured_at: string; weight_kg: number | null; waist_cm: number | null; chest_cm: number | null; arms_cm: number | null; source: string };

export default function ProgressPage() {
  const queryClient = useQueryClient(); const [showMetric, setShowMetric] = useState(false); const [weight, setWeight] = useState(""); const [waist, setWaist] = useState(""); const [sleep, setSleep] = useState("7.5"); const [energy, setEnergy] = useState("3"); const [soreness, setSoreness] = useState("2"); const [readinessResult, setReadinessResult] = useState<{ score: number; explanation: string[] } | null>(null);
  const weekly = useQuery({ queryKey: ["weekly-report"], queryFn: () => api<Report>("/reports/weekly") });
  const monthly = useQuery({ queryKey: ["monthly-report"], queryFn: () => api<Report>("/reports/monthly") });
  const metrics = useQuery({ queryKey: ["body-metrics"], queryFn: () => api<{ items: Metric[] }>("/body-metrics") });
  const addMetric = useMutation({ mutationFn: () => api("/body-metrics", { method: "POST", body: JSON.stringify({ weight_kg: weight ? Number(weight) : undefined, waist_cm: waist ? Number(waist) : undefined }) }), onSuccess: () => { setShowMetric(false); setWeight(""); setWaist(""); queryClient.invalidateQueries({ queryKey: ["body-metrics"] }); queryClient.invalidateQueries({ queryKey: ["monthly-report"] }); } });
  const readiness = useMutation({ mutationFn: () => api<{ score: number; explanation: string[] }>(`/readiness/${todayIso()}`, { method: "PUT", body: JSON.stringify({ sleep_hours: Number(sleep), energy: Number(energy), soreness: Number(soreness), stress: 3, motivation: 3, sleep_quality: 3 }) }), onSuccess: setReadinessResult });
  function submitMetric(event: FormEvent) { event.preventDefault(); addMetric.mutate(); }
  if (weekly.isLoading || monthly.isLoading || metrics.isLoading) return <LoadingState label="Calculating your progress…" />;
  if (weekly.isError || monthly.isError || metrics.isError || !weekly.data || !monthly.data || !metrics.data) return <ErrorState message={weekly.error?.message ?? monthly.error?.message ?? metrics.error?.message} />;
  const history = metrics.data.items.toReversed().filter((item) => item.weight_kg != null).map((item) => ({ date: new Date(item.measured_at).toLocaleDateString("en", { month: "short", day: "numeric" }), weight: item.weight_kg })); const latest = metrics.data.items.find((item) => item.weight_kg != null);
  return <><header className="page-head"><div><span className="eyebrow">Progress intelligence</span><h1>Your work, in context.</h1><p>Weekly action, monthly trend and body history remain separate so one score never hides the story.</p></div><div className="head-actions"><Button variant="secondary" onClick={() => setShowMetric((value) => !value)}><Plus size={16} /> Add measurement</Button></div></header>
    {showMetric && <Card className="card-pad" style={{ marginBottom: 16 }}><form className="form-row" onSubmit={submitMetric}><label className="field"><span>Weight</span><div className="input-suffix"><input className="input" type="number" min="25" max="400" step="0.1" value={weight} onChange={(e) => setWeight(e.target.value)} /><span>kg</span></div></label><label className="field"><span>Waist</span><div className="input-suffix"><input className="input" type="number" min="30" max="250" step="0.1" value={waist} onChange={(e) => setWaist(e.target.value)} /><span>cm</span></div></label><div><Button disabled={addMetric.isPending || (!weight && !waist)}>{addMetric.isPending ? "Saving…" : "Save to history"}</Button></div></form></Card>}
    <section className="grid progress-summary"><MetricCard label="Latest weight" value={formatNumber(latest?.weight_kg)} unit="kg" note={latest ? new Date(latest.measured_at).toLocaleDateString() : "No measurement"} /><MetricCard label="Workouts this week" value={weekly.data.training.sessions_completed} unit="sessions" note={`${weekly.data.training.sets_completed} sets completed`} accent="pink" /><MetricCard label="Habit completion" value={weekly.data.habits.completion_rate} unit="%" note={`${weekly.data.habits.completions} actions logged`} accent="orange" /></section>
    <div className="report-grid" style={{ marginTop: 16 }}><Card className="chart-card"><div className="section-title" style={{ margin: 0 }}><h2><Scale size={17} style={{ display: "inline" }} /> Weight history</h2><span className="pill">All records</span></div>{history.length ? <><div className="chart-wrap" aria-label={`Weight history with ${history.length} measurements`}><ResponsiveContainer width="100%" height="100%"><LineChart data={history}><CartesianGrid stroke="#222c4f" vertical={false} /><XAxis dataKey="date" stroke="#68728d" fontSize={11} tickLine={false} axisLine={false} /><YAxis stroke="#68728d" fontSize={11} tickLine={false} axisLine={false} domain={["dataMin - 1", "dataMax + 1"]} /><Tooltip contentStyle={{ background: "#111935", border: "1px solid #344065", borderRadius: 12 }} /><Line type="monotone" dataKey="weight" stroke="#ff2079" strokeWidth={3} dot={{ fill: "#ff2079", r: 4 }} /></LineChart></ResponsiveContainer></div><p className="tiny">{weekly.data.data_note}</p></> : <div className="state-card">Add a second weight measurement to build a trend.</div>}</Card>
      <Card className="chart-card"><div className="section-title" style={{ margin: 0 }}><h2><BarChart3 size={17} style={{ display: "inline" }} /> Monthly output</h2><span className="pill">Current month</span></div><div className="feature-grid" style={{ gridTemplateColumns: "repeat(2,1fr)", marginTop: 25 }}><div><span className="tiny">Training volume</span><div className="report-number">{formatNumber(monthly.data.training.volume_kg, 0)} <small className="tiny">kg</small></div></div><div><span className="tiny">Completed sessions</span><div className="report-number">{monthly.data.training.sessions_completed}</div></div><div><span className="tiny">Completed sets</span><div className="report-number">{monthly.data.training.sets_completed}</div></div><div><span className="tiny">Habit adherence</span><div className="report-number">{monthly.data.habits.completion_rate}%</div></div></div><p className="tiny" style={{ marginTop: 24 }}>Comparison uses calendar periods in your profile timezone. Partial months are clearly labeled before production release.</p></Card></div>
    <div className="report-grid" style={{ marginTop: 16 }} id="readiness"><Card className="report-card"><span className="eyebrow"><Activity size={13} style={{ display: "inline" }} /> Daily readiness</span><h3 style={{ marginTop: 12 }}>A 30-second recovery check-in</h3><div className="form-row"><label className="field"><span>Sleep hours</span><input className="input" type="number" min="0" max="16" step="0.5" value={sleep} onChange={(e) => setSleep(e.target.value)} /></label><label className="field"><span>Energy · {energy}/5</span><input type="range" min="1" max="5" value={energy} onChange={(e) => setEnergy(e.target.value)} /></label><label className="field"><span>Soreness · {soreness}/5</span><input type="range" min="1" max="5" value={soreness} onChange={(e) => setSoreness(e.target.value)} /></label></div><Button variant="secondary" onClick={() => readiness.mutate()} disabled={readiness.isPending}>{readiness.isPending ? "Calculating…" : "Calculate readiness"}</Button>{readinessResult && <div style={{ marginTop: 18 }}><div className="report-number">{readinessResult.score}<small className="tiny"> / 100</small></div>{readinessResult.explanation.map((reason) => <p className="tiny" key={reason}>{reason}</p>)}</div>}<p className="tiny" style={{ marginTop: 15 }}>Readiness is explainable fitness guidance, not medical advice.</p></Card>
      <Card className="report-card"><span className="eyebrow"><TrendingUp size={13} style={{ display: "inline" }} /> This week</span><ul className="report-list"><li><span><Dumbbell size={13} style={{ display: "inline" }} /> Sessions</span><strong>{weekly.data.training.sessions_completed} / {weekly.data.training.sessions_started}</strong></li><li><span><Flame size={13} style={{ display: "inline" }} /> Volume</span><strong>{formatNumber(weekly.data.training.volume_kg, 0)} kg</strong></li><li><span>Weight change</span><strong>{weekly.data.body.weight_change_kg == null ? "Need more data" : `${weekly.data.body.weight_change_kg > 0 ? "+" : ""}${weekly.data.body.weight_change_kg} kg`}</strong></li></ul></Card></div>
  </>;
}

