"use client";

import { useMutation, useQuery } from "@tanstack/react-query";
import { Download, ExternalLink, LockKeyhole, LogOut, ScanLine, ShieldCheck, Trash2, UserRound } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";

import { Button, Card, ErrorState, LoadingState } from "@/components/primitives";
import { api } from "@/lib/api";

type Profile = { unit_system: string; country: string; experience_level: string | null; training_type: string | null; primary_goal: string | null; equipment: string[]; schedule: Record<string, unknown> };
type Consent = { type: string; version: string; granted: boolean; granted_at: string | null; revoked_at: string | null };

export default function SettingsPage() {
  const router = useRouter(); const [confirmDelete, setConfirmDelete] = useState(false);
  const profile = useQuery({ queryKey: ["profile"], queryFn: () => api<{ profile: Profile }>("/me/profile") });
  const consents = useQuery({ queryKey: ["consents"], queryFn: () => api<{ items: Consent[] }>("/privacy/consents") });
  const toggleConsent = useMutation({ mutationFn: ({ type, granted }: { type: string; granted: boolean }) => api(`/privacy/consents/${type}`, { method: "PUT", body: JSON.stringify({ granted, version: "1.0" }) }), onSuccess: () => consents.refetch() });
  const logout = useMutation({ mutationFn: () => api("/auth/logout", { method: "POST" }), onSuccess: () => router.replace("/login") });
  const deletion = useMutation({ mutationFn: () => api("/account", { method: "DELETE" }), onSuccess: () => router.replace("/") });
  const downloadExport = async () => { const data = await api<Record<string, unknown>>("/account/export"); const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `athleteos-export-${new Date().toISOString().slice(0,10)}.json`; anchor.click(); URL.revokeObjectURL(url); };
  if (profile.isLoading || consents.isLoading) return <LoadingState label="Loading your controls…" />; if (profile.isError || consents.isError || !profile.data || !consents.data) return <ErrorState message={profile.error?.message ?? consents.error?.message} />;
  const getConsent = (type: string) => consents.data.items.find((item) => item.type === type)?.granted ?? false;
  return <><header className="page-head"><div><span className="eyebrow">Profile & controls</span><h1>Settings</h1><p>Change privacy choices and inspect what your current plan uses.</p></div></header><div className="settings-grid"><div className="dashboard-stack"><Card className="settings-section"><span className="eyebrow"><UserRound size={13} style={{ display: "inline" }} /> Athlete profile</span><div className="settings-list"><div className="settings-row"><div>Training type<small>{profile.data.profile.training_type?.replaceAll("_", " ") ?? "Not set"}</small></div><Button variant="ghost" onClick={() => router.push("/onboarding")}>Review <ExternalLink size={14} /></Button></div><div className="settings-row"><div>Primary outcome<small>{profile.data.profile.primary_goal?.replaceAll("_", " ") ?? "Not set"}</small></div></div><div className="settings-row"><div>Experience level<small>{profile.data.profile.experience_level?.replaceAll("_", " ") ?? "Not set"}</small></div></div><div className="settings-row"><div>Unit system<small>{profile.data.profile.unit_system}</small></div></div></div></Card>
      <Card className="settings-section"><span className="eyebrow"><ShieldCheck size={13} style={{ display: "inline" }} /> Purpose-specific consent</span><div className="settings-list">{[["cv_processing", "Visual analysis", "Allow derived browser-side pose data"], ["analytics", "Product analytics", "Non-sensitive usage events"], ["research", "Future research", "Separate opt-in; off by default"]].map(([type, label, copy]) => { const granted = getConsent(type); return <div className="settings-row" key={type}><div>{label}<small>{copy}</small></div><button className={`toggle ${granted ? "on" : ""}`} aria-label={`${granted ? "Disable" : "Enable"} ${label}`} aria-pressed={granted} onClick={() => toggleConsent.mutate({ type, granted: !granted })} /></div>; })}</div></Card></div>
      <aside className="dashboard-stack"><Card className="settings-section"><span className="eyebrow"><LockKeyhole size={13} style={{ display: "inline" }} /> Account</span><div className="settings-list"><div className="settings-row"><div>Export account<small>Download current account metadata</small></div><button className="icon-button" onClick={downloadExport}><Download size={16} /></button></div><div className="settings-row"><div>Sign out<small>Revokes active sessions</small></div><button className="icon-button" onClick={() => logout.mutate()}><LogOut size={16} /></button></div></div></Card><Card className="settings-section"><span className="eyebrow"><ScanLine size={13} style={{ display: "inline" }} /> Scan storage</span><p className="tiny" style={{ marginTop: 13 }}>Raw progress-photo storage is disabled in this MVP. Saved scan records contain derived geometry only and can be deleted from Body Scan.</p></Card><Card className="settings-section" style={{ borderColor: "rgba(255,83,104,.28)" }}><span className="eyebrow" style={{ color: "var(--danger)" }}>Danger zone</span>{confirmDelete ? <><p className="tiny" style={{ marginTop: 12 }}>This queues account deletion and signs you out. Production retention workers must complete irreversible purging.</p><Button variant="danger" className="button-wide" disabled={deletion.isPending} onClick={() => deletion.mutate()}><Trash2 size={15} /> {deletion.isPending ? "Queuing…" : "Confirm deletion"}</Button></> : <Button variant="danger" className="button-wide" style={{ marginTop: 15 }} onClick={() => setConfirmDelete(true)}>Request account deletion</Button>}</Card></aside></div></>;
}

