"""initial_schema

Revision ID: af59cfe3b757
Revises: 
Create Date: 2026-08-11 14:19:27.810131
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "af59cfe3b757"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('primary_muscles', sa.JSON(), nullable=False),
    sa.Column('secondary_muscles', sa.JSON(), nullable=False),
    sa.Column('movement_pattern', sa.String(length=48), nullable=False),
    sa.Column('equipment', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.String(length=32), nullable=False),
    sa.Column('training_types', sa.JSON(), nullable=False),
    sa.Column('modality', sa.String(length=32), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('safety_notes', sa.Text(), nullable=False),
    sa.Column('default_sets', sa.Integer(), nullable=False),
    sa.Column('default_rep_min', sa.Integer(), nullable=True),
    sa.Column('default_rep_max', sa.Integer(), nullable=True),
    sa.Column('default_seconds', sa.Integer(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=24), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_slug'), 'exercises', ['slug'], unique=True)
    op.create_table('foods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_name', sa.String(length=160), nullable=False),
    sa.Column('normalized_name', sa.String(length=180), nullable=False),
    sa.Column('food_type', sa.String(length=32), nullable=False),
    sa.Column('cuisine', sa.String(length=48), nullable=False),
    sa.Column('diet_type', sa.String(length=24), nullable=False),
    sa.Column('energy_kcal', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carb_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_version', sa.String(length=24), nullable=False),
    sa.Column('data_quality', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foods_normalized_name'), 'foods', ['normalized_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('athlete_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('unit_system', sa.String(length=16), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('activity_level', sa.String(length=32), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('water_target_ml', sa.Integer(), nullable=True),
    sa.Column('experience_level', sa.String(length=32), nullable=True),
    sa.Column('training_type', sa.String(length=32), nullable=True),
    sa.Column('primary_goal', sa.String(length=48), nullable=True),
    sa.Column('equipment', sa.JSON(), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.Column('dietary_preferences', sa.JSON(), nullable=False),
    sa.Column('limitation_notes', sa.Text(), nullable=True),
    sa.Column('onboarding_step', sa.Integer(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_token_hash'), 'auth_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('consent_type', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'consent_type', name='uq_user_consent_type')
    )
    op.create_index(op.f('ix_consents_user_id'), 'consents', ['user_id'], unique=False)
    op.create_table('food_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('food_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=160), nullable=False),
    sa.Column('normalized_alias', sa.String(length=180), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_aliases_food_id'), 'food_aliases', ['food_id'], unique=False)
    op.create_index(op.f('ix_food_aliases_normalized_alias'), 'food_aliases', ['normalized_alias'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('serving_options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('food_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serving_options_food_id'), 'serving_options', ['food_id'], unique=False)
    op.create_table('body_metric_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('athlete_id', sa.String(length=36), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('chest_cm', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('shoulders_cm', sa.Float(), nullable=True),
    sa.Column('arms_cm', sa.Float(), nullable=True),
    sa.Column('thighs_cm', sa.Float(), nullable=True),
    sa.Column('hips_cm', sa.Float(), nullable=True),
    sa.Column('neck_cm', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_metric_entries_athlete_id'), 'body_metric_entries', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_body_metric_entries_measured_at'), 'body_metric_entries', ['measured_at'], unique=False)
    op.create_table('cv_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('athlete_id', sa.String(length=36), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capture_type', sa.String(length=24), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('feature_schema_version', sa.String(length=32), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('quality_flags', sa.JSON(), nullable=False),
    sa.Column('derived_features', sa.JSON(), nullable=False),
    sa.Column('raw_media_stored', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_assessments_athlete_id'), 'cv_assessments', ['athlete_id'], unique=False)
    op.create_table('habits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('athlete_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('measurement_type', sa.String(length=24), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('target_unit', sa.String(length=24), nullable=True),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('derived_source', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habits_athlete_id'), 'habits', ['athlete_id'], unique=False)
    op.create_table('meal_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('athlete_id', sa.String(length=36), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'local_date', 'meal_type', name='uq_meal_day_type')
    )
    op.create_index(op.f('ix_meal_logs_athlete_id'), 'meal_logs', ['athlete_id'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('athlete_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('generator_version', sa.String(length=24), nullable=False),
    sa.Column('rationale', sa.JSON(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_athlete_id'), 'programs', ['athlete_id'], unique=False)
    op.create_table('readiness_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('athlete_id', sa.String(length=36), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('soreness', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('motivation', sa.Integer(), nullable=True),
    sa.Column('stress', sa.Integer(), nullable=True),
    sa.Column('resting_heart_rate', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'local_date', name='uq_readiness_day')
    )
    op.create_index(op.f('ix_readiness_logs_athlete_id'), 'readiness_logs', ['athlete_id'], unique=False)
    op.create_table('recommendation_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('athlete_id', sa.String(length=36), nullable=False),
    sa.Column('decision_type', sa.String(length=48), nullable=False),
    sa.Column('evidence_snapshot', sa.JSON(), nullable=False),
    sa.Column('rule_set_version', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('safety_checks', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_decisions_athlete_id'), 'recommendation_decisions', ['athlete_id'], unique=False)
    op.create_table('water_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('athlete_id', sa.String(length=36), nullable=False),
    sa.Column('amount_ml', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('client_operation_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_operation_id')
    )
    op.create_index(op.f('ix_water_logs_athlete_id'), 'water_logs', ['athlete_id'], unique=False)
    op.create_table('habit_completions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('habit_id', sa.String(length=36), nullable=False),
    sa.Column('athlete_id', sa.String(length=36), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'athlete_id', 'local_date', name='uq_habit_completion_day')
    )
    op.create_index(op.f('ix_habit_completions_athlete_id'), 'habit_completions', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_habit_completions_habit_id'), 'habit_completions', ['habit_id'], unique=False)
    op.create_table('meal_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meal_log_id', sa.String(length=36), nullable=False),
    sa.Column('food_id', sa.String(length=36), nullable=False),
    sa.Column('food_name_snapshot', sa.String(length=160), nullable=False),
    sa.Column('consumed_grams', sa.Float(), nullable=False),
    sa.Column('serving_label', sa.String(length=64), nullable=False),
    sa.Column('energy_kcal', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carb_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('source_snapshot', sa.String(length=96), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['meal_log_id'], ['meal_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_items_meal_log_id'), 'meal_items', ['meal_log_id'], unique=False)
    op.create_table('program_days',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('focus', sa.JSON(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'day_index', name='uq_program_day_index')
    )
    op.create_index(op.f('ix_program_days_program_id'), 'program_days', ['program_id'], unique=False)
    op.create_table('prescribed_exercises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('program_day_id', sa.String(length=36), nullable=False),
    sa.Column('exercise_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=False),
    sa.Column('rep_min', sa.Integer(), nullable=True),
    sa.Column('rep_max', sa.Integer(), nullable=True),
    sa.Column('target_seconds', sa.Integer(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('target_rir', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['program_day_id'], ['program_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescribed_exercises_program_day_id'), 'prescribed_exercises', ['program_day_id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('athlete_id', sa.String(length=36), nullable=False),
    sa.Column('program_day_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_rpe', sa.Integer(), nullable=True),
    sa.Column('rating', sa.String(length=24), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_volume_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_day_id'], ['program_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_athlete_id'), 'workout_sessions', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_program_day_id'), 'workout_sessions', ['program_day_id'], unique=False)
    op.create_table('personal_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('athlete_id', sa.String(length=36), nullable=False),
    sa.Column('exercise_id', sa.String(length=36), nullable=False),
    sa.Column('workout_session_id', sa.String(length=36), nullable=False),
    sa.Column('record_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_records_athlete_id'), 'personal_records', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_personal_records_exercise_id'), 'personal_records', ['exercise_id'], unique=False)
    op.create_table('set_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workout_session_id', sa.String(length=36), nullable=False),
    sa.Column('prescribed_exercise_id', sa.String(length=36), nullable=False),
    sa.Column('set_index', sa.Integer(), nullable=False),
    sa.Column('client_operation_id', sa.String(length=64), nullable=False),
    sa.Column('load_kg', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('seconds', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('assistance_kg', sa.Float(), nullable=True),
    sa.Column('rir', sa.Integer(), nullable=True),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prescribed_exercise_id'], ['prescribed_exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_operation_id'),
    sa.UniqueConstraint('workout_session_id', 'prescribed_exercise_id', 'set_index', name='uq_session_prescription_set')
    )
    op.create_index(op.f('ix_set_logs_prescribed_exercise_id'), 'set_logs', ['prescribed_exercise_id'], unique=False)
    op.create_index(op.f('ix_set_logs_workout_session_id'), 'set_logs', ['workout_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_set_logs_workout_session_id'), table_name='set_logs')
    op.drop_index(op.f('ix_set_logs_prescribed_exercise_id'), table_name='set_logs')
    op.drop_table('set_logs')
    op.drop_index(op.f('ix_personal_records_exercise_id'), table_name='personal_records')
    op.drop_index(op.f('ix_personal_records_athlete_id'), table_name='personal_records')
    op.drop_table('personal_records')
    op.drop_index(op.f('ix_workout_sessions_program_day_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_athlete_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_prescribed_exercises_program_day_id'), table_name='prescribed_exercises')
    op.drop_table('prescribed_exercises')
    op.drop_index(op.f('ix_program_days_program_id'), table_name='program_days')
    op.drop_table('program_days')
    op.drop_index(op.f('ix_meal_items_meal_log_id'), table_name='meal_items')
    op.drop_table('meal_items')
    op.drop_index(op.f('ix_habit_completions_habit_id'), table_name='habit_completions')
    op.drop_index(op.f('ix_habit_completions_athlete_id'), table_name='habit_completions')
    op.drop_table('habit_completions')
    op.drop_index(op.f('ix_water_logs_athlete_id'), table_name='water_logs')
    op.drop_table('water_logs')
    op.drop_index(op.f('ix_recommendation_decisions_athlete_id'), table_name='recommendation_decisions')
    op.drop_table('recommendation_decisions')
    op.drop_index(op.f('ix_readiness_logs_athlete_id'), table_name='readiness_logs')
    op.drop_table('readiness_logs')
    op.drop_index(op.f('ix_programs_athlete_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_meal_logs_athlete_id'), table_name='meal_logs')
    op.drop_table('meal_logs')
    op.drop_index(op.f('ix_habits_athlete_id'), table_name='habits')
    op.drop_table('habits')
    op.drop_index(op.f('ix_cv_assessments_athlete_id'), table_name='cv_assessments')
    op.drop_table('cv_assessments')
    op.drop_index(op.f('ix_body_metric_entries_measured_at'), table_name='body_metric_entries')
    op.drop_index(op.f('ix_body_metric_entries_athlete_id'), table_name='body_metric_entries')
    op.drop_table('body_metric_entries')
    op.drop_index(op.f('ix_serving_options_food_id'), table_name='serving_options')
    op.drop_table('serving_options')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_food_aliases_normalized_alias'), table_name='food_aliases')
    op.drop_index(op.f('ix_food_aliases_food_id'), table_name='food_aliases')
    op.drop_table('food_aliases')
    op.drop_index(op.f('ix_consents_user_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_token_hash'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_table('athlete_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_foods_normalized_name'), table_name='foods')
    op.drop_table('foods')
    op.drop_index(op.f('ix_exercises_slug'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
